/** Haircut presets. Length is centimetres above the hairline on the photo. Beard is how much of the beard in the photo to keep. */
export const PRESETS = [
  {
    id: "actual",
    name: "Tu corte",
    detail: "Crop rizado, degradado medio",
    photo: true,
    lengthCm: 4.8,
    fade: 0.72,
    curl: 0.7,
    curlFreq: 2.4,
    volume: 0.42,
    gravity: 0.62,
    flow: -0.05,
    part: 0.0,
    spread: 0.28,
    backMul: 0.72,
    fringe: 1.18,
    mohawk: 0,
    density: 1,
    mess: 0.22,
    stubbleCm: 0.15,
    beard: 1,
    beardStyle: "full",
  },
  {
    id: "fade-alto",
    name: "Degradado alto",
    detail: "Arriba texturizado, lados a piel",
    lengthCm: 4.6,
    fade: 0.9,
    curl: 0.7,
    curlFreq: 3.0,
    volume: 0.5,
    gravity: 0.42,
    flow: -0.02,
    part: 0.1,
    spread: 0.22,
    backMul: 0.38,
    fringe: 1.05,
    mohawk: 0,
    density: 1,
    mess: 0.36,
    stubbleCm: 0.18,
    beard: 1,
    beardStyle: "full",
  },
  {
    id: "crop",
    name: "Crop texturizado",
    detail: "Corto arriba, flequillo suave",
    lengthCm: 3.4,
    fade: 0.68,
    curl: 0.32,
    curlFreq: 2.2,
    volume: 0.28,
    gravity: 0.58,
    flow: -0.45,
    part: 0.0,
    spread: 0.18,
    backMul: 0.55,
    fringe: 1.35,
    mohawk: 0,
    density: 1,
    mess: 0.3,
    stubbleCm: 0.2,
    beard: 1,
    beardStyle: "full",
  },
  {
    id: "french",
    name: "French crop",
    detail: "Flequillo recto y corto",
    lengthCm: 2.6,
    fade: 0.74,
    curl: 0.12,
    curlFreq: 1.4,
    volume: 0.16,
    gravity: 0.78,
    flow: -0.92,
    part: 0.0,
    spread: 0.08,
    backMul: 0.48,
    fringe: 1.55,
    mohawk: 0,
    density: 1,
    mess: 0.16,
    stubbleCm: 0.18,
    beard: 1,
    beardStyle: "full",
  },
  {
    id: "caesar",
    name: "Caesar",
    detail: "Flequillo corto hacia la frente",
    lengthCm: 2.3,
    fade: 0.42,
    curl: 0.08,
    curlFreq: 1.2,
    volume: 0.12,
    gravity: 0.86,
    flow: -1,
    part: 0.0,
    spread: 0.05,
    backMul: 0.75,
    fringe: 1.7,
    mohawk: 0,
    density: 0.9,
    mess: 0.1,
    stubbleCm: 0.25,
    beard: 1,
    beardStyle: "full",
  },
  {
    id: "slick",
    name: "Hacia atrás",
    detail: "Peinado liso, degradado bajo",
    lengthCm: 8.5,
    fade: 0.34,
    curl: 0.16,
    curlFreq: 1.5,
    volume: 0.22,
    gravity: 0.4,
    flow: 0.95,
    part: 0.2,
    spread: 0.16,
    backMul: 1.15,
    fringe: 0.62,
    mohawk: 0,
    density: 0.92,
    mess: 0.14,
    stubbleCm: 0.3,
    beard: 1,
    beardStyle: "full",
  },
  {
    id: "raya",
    name: "Raya al lado",
    detail: "Clásico, con raya marcada",
    lengthCm: 8,
    fade: 0.2,
    curl: 0.22,
    curlFreq: 1.6,
    volume: 0.3,
    gravity: 0.52,
    flow: 0.15,
    part: 0.78,
    spread: 0.72,
    backMul: 1,
    fringe: 1.15,
    mohawk: 0,
    density: 0.95,
    mess: 0.18,
    stubbleCm: 0.35,
    beard: 1,
    beardStyle: "full",
  },
  {
    id: "undercut",
    name: "Undercut",
    detail: "Lados rapados, arriba desconectado",
    lengthCm: 9,
    fade: 0.98,
    curl: 0.4,
    curlFreq: 2.2,
    volume: 0.38,
    gravity: 0.36,
    flow: 0.35,
    part: 0.55,
    spread: 0.3,
    backMul: 0.42,
    fringe: 0.9,
    mohawk: 0,
    density: 1,
    mess: 0.22,
    stubbleCm: 0.12,
    beard: 1,
    beardStyle: "full",
  },
  {
    id: "afro",
    name: "Afro corto",
    detail: "Volumen redondo, rizo cerrado",
    lengthCm: 5.5,
    fade: 0.02,
    curl: 1,
    curlFreq: 4.4,
    volume: 1,
    gravity: 0.06,
    flow: 0,
    part: 0,
    spread: 0.12,
    backMul: 1.2,
    fringe: 1.05,
    mohawk: 0,
    density: 1,
    mess: 0.28,
    stubbleCm: 0.4,
    beard: 1,
    beardStyle: "full",
  },
  {
    id: "rulos",
    name: "Rulos medios",
    detail: "Más largo, lados con volumen",
    lengthCm: 11,
    fade: 0.12,
    curl: 0.92,
    curlFreq: 3.3,
    volume: 0.78,
    gravity: 0.48,
    flow: -0.12,
    part: 0,
    spread: 0.34,
    backMul: 1.25,
    fringe: 1.25,
    mohawk: 0,
    density: 0.9,
    mess: 0.4,
    stubbleCm: 0.45,
    beard: 1,
    beardStyle: "full",
  },
  {
    id: "mullet",
    name: "Mullet",
    detail: "Corto adelante, largo atrás",
    lengthCm: 4.2,
    fade: 0.5,
    curl: 0.38,
    curlFreq: 2.1,
    volume: 0.32,
    gravity: 0.5,
    flow: -0.15,
    part: 0,
    spread: 0.2,
    backMul: 2.6,
    fringe: 1.1,
    mohawk: 0,
    density: 0.95,
    mess: 0.34,
    stubbleCm: 0.22,
    beard: 1,
    beardStyle: "full",
  },
  {
    id: "cortinas",
    name: "Cortinas",
    detail: "Flequillo partido, textura media",
    lengthCm: 10,
    fade: 0.18,
    curl: 0.55,
    curlFreq: 2.4,
    volume: 0.58,
    gravity: 0.46,
    flow: -0.42,
    part: 0,
    spread: 0.95,
    backMul: 1.2,
    fringe: 1.65,
    mohawk: 0,
    density: 0.92,
    mess: 0.38,
    stubbleCm: 0.3,
    beard: 1,
    beardStyle: "full",
  },
  {
    id: "mohawk",
    name: "Mohawk",
    detail: "Cresta al centro, lados a piel",
    lengthCm: 8,
    fade: 0.92,
    curl: 0.28,
    curlFreq: 1.8,
    volume: 0.66,
    gravity: 0.22,
    flow: 0.05,
    part: 0,
    spread: 0.08,
    backMul: 0.85,
    fringe: 1,
    mohawk: 0.88,
    density: 1,
    mess: 0.2,
    stubbleCm: 0.12,
    beard: 1,
    beardStyle: "full",
  },
  {
    id: "buzz",
    name: "Buzz cut",
    detail: "Uniforme, casi al ras",
    lengthCm: 0.7,
    fade: 0.35,
    curl: 0.04,
    curlFreq: 1,
    volume: 0.04,
    gravity: 0.2,
    flow: 0,
    part: 0,
    spread: 0,
    backMul: 0.8,
    fringe: 0.8,
    mohawk: 0,
    density: 0.75,
    mess: 0.05,
    stubbleCm: 0.35,
    beard: 1,
    beardStyle: "full",
  },
  {
    id: "rapado",
    name: "Rapado",
    detail: "Piel, con sombra de cabello",
    lengthCm: 0.15,
    fade: 1,
    curl: 0,
    curlFreq: 1,
    volume: 0,
    gravity: 0,
    flow: 0,
    part: 0,
    spread: 0,
    backMul: 1,
    fringe: 1,
    mohawk: 0,
    density: 0.35,
    mess: 0,
    stubbleCm: 0.12,
    beard: 0,
    beardStyle: "full",
  },
  {
    id: "largo",
    name: "Ondulado largo",
    detail: "Dejado crecer, onda natural",
    lengthCm: 16,
    fade: 0.04,
    curl: 0.62,
    curlFreq: 2.2,
    volume: 0.5,
    gravity: 0.74,
    flow: -0.05,
    part: 0.15,
    spread: 0.4,
    backMul: 1.35,
    fringe: 1.35,
    mohawk: 0,
    density: 0.82,
    mess: 0.36,
    stubbleCm: 0.5,
    beard: 1,
    beardStyle: "full",
  },
];

export const HAIR_COLORS = [
  { id: "natural", name: "Tu color", tint: null },
  { id: "negro", name: "Negro", tint: [0.035, 0.03, 0.03] },
  { id: "castano", name: "Castaño", tint: [0.18, 0.1, 0.06] },
  { id: "cobrizo", name: "Cobrizo", tint: [0.32, 0.13, 0.07] },
  { id: "rubio", name: "Rubio oscuro", tint: [0.45, 0.32, 0.16] },
  { id: "platino", name: "Platinado", tint: [0.72, 0.68, 0.58] },
  { id: "canas", name: "Canoso", tint: [0.55, 0.54, 0.52] },
];

export const BEARD_STYLES = [
  { id: "full", name: "Completa" },
  { id: "goatee", name: "Candado" },
  { id: "mustache", name: "Bigote" },
];

export function fadeLabel(fade) {
  if (fade < 0.18) return "Sin degradado";
  if (fade < 0.42) return "Bajo";
  if (fade < 0.68) return "Medio";
  if (fade < 0.86) return "Alto";
  return "A piel";
}
